Repository CertifaiAI/basics-of-data-analytics, pull requests merged in 2021-06, with the labels that each got.

#12 Create LICENSE
  LICENSE
Labels: documentation

#13 Create PR & Issue Templates
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/---documentation.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#15 :memo: updated README.md
  README.md
Labels: documentation

#14 Adding execution test workflow for Jupyter Notebook
  .github/workflows/test_jupyter.yml
Labels: ci/cd, enhancement

#18 Update environment file & code test workflow
  .github/workflows/test_jupyter.yml
  environment.yml
Labels: bug, ci/cd, enhancement
